AWSTemplateFormatVersion: 2010-09-09
Description: Stack for creating CT Tagging Solution using Control Tower Lifecycle Events

Parameters:
  
  EventBusName:
    Type: String
    Description: Select name of the dedicated event bus that will be created at the Hub account
    Default: VPCTagging-EventBus

  S3BucketName:
    Type: String
    Description: Enter the Name of the existing S3 bucket where the Lambda code was uploaded

  S3LambdaZipName: 
    Type: String
    Description: Enter file name of Lambda Zip - i.e. ControlTowerLifeCycleEventLambda-AutomatedVPCTagging.zip 

Resources:
  VPCTaggingEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Ref EventBusName

  VPCTaggingEventBusPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
        Action: "events:PutEvents"
        Principal: "*"
        StatementId: "AllowAllAccountPutEventsToBus"
        EventBusName: !Ref VPCTaggingEventBus

  VPCTaggingLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: VPCTaggingLambdaRole
      Description: Role used by Lambda to assume VPCTaggingRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
      - PolicyName: VPCTaggingLambdaRoleAssumePolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Resource: 
              - "arn:aws:iam::*:role/AWSControlTowerExecution"
      ManagedPolicyArns:
              - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
              
  VPCTaggingLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Sub ${AWS::AccountId}-ControlTowerLifeCycleEventLambda-AutomatedVPCTagging
      Description: VPCTagging - Function to handle incoming events and tag VPC resources inside new account
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt VPCTaggingLambdaRole.Arn
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3LambdaZipName
      Runtime: "python3.7"
      MemorySize: 128
      Timeout: 300
      ReservedConcurrentExecutions: 500

  VPCTaggingTagHubRule:
    DependsOn:
      - VPCTaggingEventBus
    Type: AWS::Events::Rule
    Properties:
      Name: VPCTagging-HubRule
      Description: VPCTagging Trigger for Lambda to execute tagging across VPC resources for new account
      EventBusName: !Ref EventBusName
      EventPattern:
        {
          "source": ["aws.controltower"],
          "detail-type": ["AWS Service Event via CloudTrail"],
          "detail": {
            "eventName": ["CreateManagedAccount"]
          }
        }
      State: ENABLED
      Targets:
        - Arn: !GetAtt VPCTaggingLambdaFunction.Arn
          Id: "TagCreateUpdateHubTrigger"
